### ISSUE TITLE
German Amazon character issue

### ISSUE THREAD

**Issue by carloswear** [tducret/amazon-scraper-python#18]
Thank you very much, this app is very easy to use and powerful.

I have a small question, why do the German Amazon information I grabed have a lot of "?" garbled.

How can I solve this? @tducret 

Carlos
![del](https://user-images.githubusercontent.com/41362266/51101663-7acb4600-1816-11e9-9066-d5b23d0e711d.png)

**Comment by tducret** [comment]
Hi @carloswear 
What kind of spreadsheet editor are you using?

I have the same problem with Mac Excel 2011, since it apparently doesn't support UTF-8 (https://rothmanshore.com/2013/10/29/solved-editing-a-csv-with-utf-8-encoding-on-a-mac/)

As a workaround, you may open it with Google spreadsheet, and then export it to xlsx.

Here is a snapshot with the same kind of data.
![snapshot_mac_excel_after_export_google_spreadsheet](https://user-images.githubusercontent.com/2735014/51132013-78c2b080-1831-11e9-8e9d-e766e2204a47.png)
